name: my_projects
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  lottie: ^1.4.2
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  dartz: ^0.10.1
  fluttertoast: ^8.0.9
  flutter_cube: ^0.1.1
  font_awesome_flutter: ^10.1.0
  http: ^0.13.5
  internet_connection_checker: ^0.0.1+4
  connectivity_plus: ^2.3.6+1
  get_it: ^7.2.0
  device_preview: ^1.1.0
  intl: ^0.17.0
  flutter_svg: ^1.1.3
  weather_icons: ^3.0.0
  geolocator: ^8.1.0
  webview_flutter: ^3.0.4
  flutter_map: ^1.1.1
  responsive_framework: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/lottie/
    - assets/images/
    - assets/objects/dice/

  fonts:
    - family: mat
      fonts:
        - asset: assets/fonts/maturasc.ttf

    - family: bsan
      fonts:
        - asset: assets/fonts/BalsamiqSan.ttf

    - family: sen
      fonts:
        - asset: assets/fonts/Sen-Bold.ttf
        - asset: assets/fonts/Sen-Regular.ttf

    - family: bahnsch
      fonts:
        - asset: assets/fonts/Bahnschrift.TTF